import React from 'react';

interface AppProps {
  appName: string;
}

const App: React.FC<AppProps> = ({ appName }) => {
  return (
    <div className="app">
      <header>
        <h1>Welcome to {{APP_NAME}}</h1>
        <p>Created by {{AUTHOR}} in {{CURRENT_YEAR}}</p>
      </header>
      <main>
        <p>This is a React application generated by ForgeCLI.</p>
      </main>
    </div>
  );
};

export default App;